spring:
  application:
    name: businessassistant-usermanagement
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    enabled: true
  data:
    mongodb:
      #uri: mongodb://localhost:27017/babcn-users
      uri: mongodb://admin_businessassistantbcn:UhWQQYFVBx95W7@localhost:27017/babcn-users
      #host: 172.24.2.9
      #host: localhost
      #port: 27017
      #username:
      #password:
      #database:
  #Spring profiles available:
  #   - dev: disable security
  #   - pro: enable JWT security
  profiles:
    active:
      - dev #pro

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

security:
  datasource:
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    authoritiesClaim: authorities
    err: Auth Error, Token Unavailable

server:
  port: 8763

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
limitdb:
  enabled: true #false
  maxusers: 200
  err: No hay capacidad para almacenar más usuarios
