version: '3.7'

services:
  consul-server1:
    image: consul:1.12.2
    container_name: consul-server1
    restart: always
    networks:
      - consul-net
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.12.2
    container_name: consul-server2
    restart: always
    networks:
      - consul-net
    command: 'agent -bootstrap-expect=3'

  consul-server3:
    image: consul:1.12.2
    container_name: consul-server3
    restart: always
    networks:
      - consul-net
    command: 'agent -bootstrap-expect=3'

  consul-client:
    image: consul:1.12.2
    container_name: consul-client
    restart: always
    volumes:
      - ./client.json:/consul/config/client.json:ro
      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul-net
    command: 'agent'

networks:
  consul-net:
    driver:
      bridge
