version: '3.7'

services:
  consul-server1:
    image: consul:1.12.2
    container_name: consul-server1
    restart: always
    volumes:
      - ./consul/server1.json:/consul/config/server1.json:ro
    networks:
      - consul-net
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.12.2
    container_name: consul-server2
    restart: always
    volumes:
      - ./consul/server2.json:/consul/config/server2.json:ro
    networks:
      - consul-net
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.12.2
    container_name: consul-server3
    restart: always
    volumes:
      - ./consul/server3.json:/consul/config/server3.json:ro
    networks:
      - consul-net
    command: "agent -bootstrap-expect=3"

networks:
  consul-net:
    driver:
      bridge
