spring:
  application:
    name: businessassistant-opendata
  jmx:
    enabled: true
  cloud:
    consul:
      #CAUTION: for development purposes only (start with Gradle's command bootRun).
      #host: localhost
      #Docker start requires container_name att as hostname
      #host: consul-server1
      host: 127.0.0.1
      port: 8500 #puerto HTTP del agente
      config:
        enabled: true
      discovery:
        instanceId: id:${spring.application.name}:${random.value}
        serviceName: name:${spring.application.name}
        enabled: true
        register: true
        register-health-check: true
        deregister: true
        port: 8762 #puerto del servicio
        prefer-ip-address: true
        healthCheckPath: /health
        #healthCheckPath: ${management.server.servlet.context-path}/health
        #healthCheckPath: /businessassistantbcn/api/v1/opendata/test
        #healthCheckPath: /actuator/health
        healthCheckInterval: 15s
  #Spring profiles available:
  #   - dev: disable security
  #   - pro: enable JWT security
  profiles:
    active:
    - dev


springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false

url:
  connection_timeout: 30000
  maxBytesInMemory: 30000000
  ds_test: https://swapi.py4e.com/api/vehicles/
  ds_largeestablishments: http://www.bcn.cat/tercerlloc/files/mercats-centrescomercials/opendatabcn_mercats-centrescomercials_grans-establiments-js.json
  ds_commercialgalleries: http://www.bcn.cat/tercerlloc/files/mercats-centrescomercials/opendatabcn_mercats-centrescomercials_galeries-comercials-js.json
  ds_bigmalls: http://www.bcn.cat/tercerlloc/files/mercats-centrescomercials/opendatabcn_mercats-centrescomercials_grans-centres-comercials-js.json
  ds_municipalmarkets: http://www.bcn.cat/tercerlloc/files/mercats-centrescomercials/opendatabcn_mercats-centrescomercials_mercats-municipals-js.json
  ds_marketfairs: http://www.bcn.cat/tercerlloc/files/mercats-centrescomercials/opendatabcn_mercats-centrescomercials_mercats-fires-al-carrer-js.json
  ds_economicactivitiescensus: https://opendata-ajuntament.barcelona.cat/data/dataset/671c46e9-5b85-4e63-8c97-088a2b907cd5/resource/7a3d5380-f79a-424e-be62-dd078efcb40a/download/2019_censcomercialbcn_class_act.json
  ds_economicactivitiesgroundfloor: https://opendata-ajuntament.barcelona.cat/data/dataset/62fb990e-4cc3-457a-aea1-497604e15659/resource/495c434e-b005-416e-b760-dc79f56dff3a/download/2019_censcomercialbcn_detall.geojson
  districts:
    - "Ciutat Vella"
    - "Eixample"
    - "Sants-Montjuïc"
    - "Les Corts"
    - "Sarrià-Sant Gervasi"
    - "Gràcia"
    - "Horta-Guinardó"
    - "Nou Barris"
    - "Sant Andreu"
    - "Sant Martí"

security:
  datasource:
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    authoritiesClaim: authorities
    err: Auth Error, Token Unavailable 
---
logging:
  level:
    root: INFO  
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
