spring:
  application:
    name: businessassistant-usermanagement
  jmx:
    enabled: true
  data:
    mongodb:
      host: 172.24.2.9
      port: 27018
      username: admin_businessassistantbcn
      password: UhWQQYFVBx95W7
      database: babcn-users
  #Spring profiles available:
  #   - dev: disable security
  #   - pro: enable JWT security
  profiles:
    active:
      - dev

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

security:
  datasource:
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    authoritiesClaim: authorities
    err: Auth Error, Token Unavailable

server:
  port: 8763

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
    # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
