version: '3.7'

services:
  consul-server1:
    image: consul:1.12.3
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.0
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.12.3
    container_name: consul-server2
    restart: always
    volumes:
      - ./server2.json:/consul/config/server2.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.1
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.12.3
    container_name: consul-server3
    restart: always
    volumes:
      - ./server3.json:/consul/config/server3.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.2
    command: "agent -bootstrap-expect=3"

  consul-client-mongodb:
    image: consul:1.12.3
    container_name: consul-client-mongodb
    restart: always
    volumes:
      - ./consul-client-mongodb.json:/consul/config/client.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.3
    command: "agent"

  businessassistantbcn-opendata:
    image: babcn:opendata-v1.0-SNAPSHOT
    container_name: opendata-v1.0-SNAPSHOT
    restart: always
    #volumes:
     # - ./consul-client-babcn.json:/consul/config/consul-client-babcn.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.4
    ports:
      - '7777:8762'

  businessassistantbcn-gencat:
    image: babcn:gencat-v1.0-SNAPSHOT
    container_name: gencat-v1.0-SNAPSHOT
    restart: always
    #volumes:
    # - ./consul-client-babcn.json:/consul/config/consul-client-babcn.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.5
    ports:
      - '7776:8762'
    #command: "consul agent -data-dir=/tmp/consul -join=172.17.0.2 -bind=172.17.0.3 -client=172.17.0.3"

  businessassistantbcn-usermanagement:
    image: babcn:usermanagement-v1.0-SNAPSHOT
    container_name: usermanagement-v1.0-SNAPSHOT
    restart: always
    #volumes:
    # - ./consul-client-babcn.json:/consul/config/consul-client-babcn.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.6
    ports:
      - '7778:8762'

  businessassistantbcn-mongodb:
    container_name: mongodb-businessassistantbcn
    image: mongo:5.0.9
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_businessassistantbcn
      MONGO_INITDB_ROOT_PASSWORD: UhWQQYFVBx95W7
      MONGO_INITDB_DATABASE: babcn-users
    ports:
      - 27017:27017
    volumes:
      - businessassistantbcn_mongodb_data:/var/lib/mongodb
      - ./BusinessAssistant-usermanagement/src/main/resources/mongodb-init:/docker-entrypoint-initdb.d
      - ./BusinessAssistant-usermanagement/src/main/resources/mongodb-test-data:/tmp/data/
    networks:
      consul-net:
        ipv4_address: 172.24.2.7


  businessassistantbcn-login:
    image: babcn:login-v1.0-SNAPSHOT
    container_name: login-v1.0-SNAPSHOT
    restart: always
    #volumes:
    # - ./consul-client-babcn.json:/consul/config/consul-client-babcn.json:ro
    networks:
      consul-net:
        ipv4_address: 172.24.2.8
    ports:
      - '7779:8761'

volumes:
  businessassistantbcn_mongodb_data:

networks:
  consul-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.2.0/16
