version: '3.7'

services:
  consul-server1:
    image: consul:1.12.3
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.json:/consul/config/server1.json:ro
    networks:
      - consul-net
    ports:
      - '8500:8500'
      - '8600:8600/tcp'
      - '8600:8600/udp'
    command: 'agent -bootstrap-expect=3'

  consul-server2:
    image: consul:1.12.3
    container_name: consul-server2
    restart: always
    volumes:
      - ./server2.json:/consul/config/server2.json:ro
    networks:
      - consul-net
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: consul:1.12.3
    container_name: consul-server3
    restart: always
    volumes:
      - ./server3.json:/consul/config/server3.json:ro
    networks:
      - consul-net
    command: "agent -bootstrap-expect=3"

  consul-client-mysql:
    image: consul:1.12.3
    container_name: consul-client-mysql
    restart: always
    volumes:
      - ./consul-client-mysql.json:/consul/config/consul-client-mysql.json:ro
    networks:
      - consul-net
    command: "agent"

  consul-client-mongodb:
    image: consul:1.12.3
    container_name: consul-client-mongodb
    restart: always
    volumes:
      - ./consul-client-mongodb.json:/consul/config/consul-client-mongodb.json:ro
    networks:
      - consul-net
    command: "agent"

  consul-client-babcn:
    image: babcn:opendata-v1.0-SNAPSHOT
    container_name: opendata-v1.0-SNAPSHOT
    restart: always
    volumes:
      - ./consul-client-babcn.json:/consul/config/consul-client-babcn.json:ro
    networks:
      - consul-net
    command: "consul agent -data-dir=/tmp/consul -join=172.17.0.2 -bind=172.17.0.3 -client=172.17.0.3"

networks:
  consul-net:
    driver:
      bridge
