spring:
  application:
    name: businessassistant-gencat
  jmx:
    enabled: true


# OJO bug afecta a Swagger
#springfox:
#  documentation:
#    auto-startup: false
#Se usa springdoc-openapi para documentar la api

springdoc:
  swagger-ui:
    path: "/swagger-ui-custom.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO  
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
