spring:
  application:
    name: businessassistant-gencat
  jmx:
    enabled: true
  #Spring profiles available:
  #   - dev: disable security
  #   - pro: enable JWT security
  profiles:
    active:
    - dev 
    
security:
  datasource:
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    authoritiesClaim: authorities
    err: Auth Error, Token Unavailable 

# OJO bug afecta a Swagger
springfox:
  documentation:
    auto-startup: false

server:
  port: 8762

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO  
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: opendata.log
